// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi2SKqdJ_WsfhkjsJheFE-foyYpFXRHzk',
    appId: '1:502955524680:web:38d08becd68f8cbbdb4e7d',
    messagingSenderId: '502955524680',
    projectId: 'quit-for-good',
    authDomain: 'quit-for-good.firebaseapp.com',
    storageBucket: 'quit-for-good.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpjSTSKpvBv7qcH5UnQ3Omg6rdRfXWd4',
    appId: '1:502955524680:android:e49a658d7f888aabdb4e7d',
    messagingSenderId: '502955524680',
    projectId: 'quit-for-good',
    storageBucket: 'quit-for-good.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ocDHn6das7fV6UUnunVP4AGUSINyJ5U',
    appId: '1:502955524680:ios:092a89a118bbde85db4e7d',
    messagingSenderId: '502955524680',
    projectId: 'quit-for-good',
    storageBucket: 'quit-for-good.appspot.com',
    iosClientId: '502955524680-musoep2c1cggo68fs15670dr79j65hr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.quitForGood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ocDHn6das7fV6UUnunVP4AGUSINyJ5U',
    appId: '1:502955524680:ios:092a89a118bbde85db4e7d',
    messagingSenderId: '502955524680',
    projectId: 'quit-for-good',
    storageBucket: 'quit-for-good.appspot.com',
    iosClientId: '502955524680-musoep2c1cggo68fs15670dr79j65hr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.quitForGood',
  );
}
